import { OUTRA_USUARIA_ID, RECEITA_ID, RECEITA_ID_2, USER_ID, type Linha } from "./fakeSupabase";

/**
 * Dados totalmente fictícios para os testes da exportação. Incluem casos
 * difíceis de propósito: texto que parece fórmula, aspas, quebra de linha,
 * acentos, numeric vindo como string (como o PostgREST entrega), nulos e zero.
 * Uma linha de outra usuária existe para testar o isolamento.
 */
export function tabelasFicticias(): Record<string, Linha[]> {
  return {
    perfil_usuario: [
      {
        user_id: USER_ID,
        nome: "=Teste Fórmula",
        altura_cm: "152.00",
        data_nascimento: "1990-05-10",
        cronograma_inicio_ciclo: "2026-09-28",
      },
      {
        user_id: OUTRA_USUARIA_ID,
        nome: "Outra Pessoa",
        altura_cm: "160.00",
        data_nascimento: "1980-01-01",
        cronograma_inicio_ciclo: null,
      },
    ],
    registros_peso: [
      {
        user_id: USER_ID,
        data: "2026-09-10",
        peso_kg: "58.10",
        percentual_gordura: "34.6",
        percentual_massa_muscular: null,
        percentual_agua: "0.00",
      },
      {
        user_id: USER_ID,
        data: "2026-09-03",
        peso_kg: "59.00",
        percentual_gordura: null,
        percentual_massa_muscular: "30.0",
        percentual_agua: null,
      },
      {
        user_id: OUTRA_USUARIA_ID,
        data: "2026-09-01",
        peso_kg: "70.00",
        percentual_gordura: null,
        percentual_massa_muscular: null,
        percentual_agua: null,
      },
    ],
    medidas_corporais: [
      { user_id: USER_ID, data: "2026-09-10", regiao: "coxa", valor_cm: "60.00" },
      { user_id: USER_ID, data: "2026-09-10", regiao: "cintura", valor_cm: "77.00" },
      { user_id: USER_ID, data: "2026-09-03", regiao: "quadril", valor_cm: "96.00" },
      { user_id: OUTRA_USUARIA_ID, data: "2026-09-10", regiao: "cintura", valor_cm: "90.00" },
    ],
    adesao_habitos: [
      {
        user_id: USER_ID,
        data: "2026-09-10",
        quantidade_agua_ml: 2000,
        priorizou_proteina: true,
        bebeu_agua_meta: false,
      },
      {
        user_id: USER_ID,
        data: "2026-09-03",
        quantidade_agua_ml: 0,
        priorizou_proteina: false,
        bebeu_agua_meta: false,
      },
      {
        user_id: OUTRA_USUARIA_ID,
        data: "2026-09-10",
        quantidade_agua_ml: 3000,
        priorizou_proteina: true,
        bebeu_agua_meta: true,
      },
    ],
    adesao_treino: [
      {
        user_id: USER_ID,
        data: "2026-09-10",
        tipo: "outro",
        tipo_outro_descricao: '-Caminhada "leve", ao ar livre\nperto de casa',
        realizado: true,
        duracao_minutos: 30,
        calorias: 0,
        obrigatorio: false,
      },
      {
        user_id: USER_ID,
        data: "2026-09-03",
        tipo: "moves",
        tipo_outro_descricao: null,
        realizado: false,
        duracao_minutos: null,
        calorias: null,
        obrigatorio: true,
      },
    ],
    metas: [
      {
        user_id: USER_ID,
        indicador: "cintura",
        fase: null,
        data_inicio: "2026-09-01",
        valor_referencia: "80.00",
        valor_meta: "75.00",
        unidade: "cm",
        prazo_estimado_semanas: 12,
        meta_hidratacao_litros_dia: null,
        created_at: "2026-08-30T12:00:00+00:00",
      },
      {
        user_id: USER_ID,
        indicador: "hidratacao",
        fase: null,
        data_inicio: "2026-09-01",
        valor_referencia: null,
        valor_meta: null,
        unidade: null,
        prazo_estimado_semanas: null,
        meta_hidratacao_litros_dia: "2.50",
        created_at: "2026-08-30T12:00:00+00:00",
      },
    ],
    receitas: [
      {
        id: RECEITA_ID,
        user_id: USER_ID,
        nome: "Frango, fictício",
        categoria: "jantar",
        ingredientes: "+100g de frango\n@ temperos",
        modo_preparo: 'Asse "bem" por 20 min',
        dica_congelamento: null,
        selos: ["air fryer", "congelável"],
        validade_congelado_dias: 90,
        notas: "Linha 1\r\nLinha 2",
      },
      {
        id: RECEITA_ID_2,
        user_id: USER_ID,
        nome: "Ovo fictício",
        categoria: null,
        ingredientes: null,
        modo_preparo: null,
        dica_congelamento: null,
        selos: [],
        validade_congelado_dias: 60,
        notas: null,
      },
    ],
    preparos: [
      {
        user_id: USER_ID,
        receita_id: RECEITA_ID,
        data_preparo: "2026-09-10",
        dia_semana: "Quinta",
        semana_ciclo: 2,
        quantidade_porcoes: "4",
        observacoes: "=SOMA(A1)",
        status: "congelado",
        data_consumo: null,
      },
      {
        user_id: USER_ID,
        receita_id: RECEITA_ID,
        data_preparo: "2026-09-03",
        dia_semana: "Quinta",
        semana_ciclo: 1,
        quantidade_porcoes: "2",
        observacoes: null,
        status: "consumido",
        data_consumo: "2026-09-05",
      },
    ],
    itens_compra: [
      {
        user_id: USER_ID,
        grupo: "despensa",
        item: "Sal marinho",
        tenho_em_casa: false,
        observacao: "@loja",
      },
      {
        user_id: USER_ID,
        grupo: "proteinas",
        item: "Frango",
        tenho_em_casa: true,
        observacao: null,
      },
    ],
    cronograma_planejado: [
      {
        user_id: USER_ID,
        semana_ciclo: 1,
        dia_semana: "Quarta",
        proteina: "Frango",
        base: null,
        legumes: "-brócolis",
        receita_extra_texto: null,
      },
      {
        user_id: USER_ID,
        semana_ciclo: 1,
        dia_semana: "Segunda",
        proteina: null,
        base: "Arroz",
        legumes: null,
        receita_extra_texto: "Receita extra",
      },
      {
        user_id: OUTRA_USUARIA_ID,
        semana_ciclo: 1,
        dia_semana: "Segunda",
        proteina: "Não deve aparecer",
        base: null,
        legumes: null,
        receita_extra_texto: null,
      },
    ],
  };
}
